const Menu = [
    {
        id: 1,
        image: "images/Burger1.webp",
        name: 'Chicken Cheese Burger',
        category: 'Burger',
        price: 25,
        description: 'Chicken Cheese Burger Lorem ipsum dolor sit amet, consectetur adip.....',
    },
    {
        id: 2,
        image: "images/Burger2.webp",
        name: "Beef Patty Burger",
        category: "Burger",
        price: "20₹",
        description:"Beef Patty Burger Lorem ipsum dolor sit amet, consectetur adip.....",
    },
    {
        id: 3,
        image: "images/Burger3.webp",
        name: "Beef Cheese Burger",
        category: "Burger",
        price: "10₹",
        description:"Beef Cheese Burger Lorem ipsum dolor sit amet, consectetur adip.....",
    },
    {
        id: 4,
        image: "../images/Burger4.webp",
        name: "Saucy Double Beef Burger",
        category: "Burger",
        price: "50₹",
        description:"Saucy Double Beef Burger Lorem ipsum dolor sit amet, consectetur adip.....",
    },
    {
        id: 5,
        image: "../images/Burger4.webp",
        name: "Trio Deal",
        category: "Burger",
        price: "80₹",
        description: "Trio Beef Burger Deal Lorem ipsum dolor sit amet, consectetur adip.....",
    },
    {
        id: 6,
        image: "images/Pizza1.jpg",
        name: 'Beef Medium Rare Steak',
        category: 'Pizza',
        price: 25,
        description: 'Beef Medium Rare Steak Lorem ipsum dolor sit amet, consectetur adip.....',
    },
    {
        id: 7,
        image: "images/Pizza2.jpg",
        name: "Pepperoni Pizza",
        category: "Pizza",
        price: "20₹",
        description:"Pepperoni Pizza Lorem ipsum dolor sit amet, consectetur adip.....",
    },
    {
        id: 8,
        image: "images/Pizza3.jpg",
        name: "Full Cheese Pizza",
        category: "Pizza",
        price: "10₹",
        description:"Full Cheese Pizza Lorem ipsum dolor sit amet, consectetur adip.....",
    },
    {
        id: 9,
        image: "../images/Pizza4.jpg",
        name: "Saucy Cheesy Pizza",
        category: "Pizza",
        price: "50₹",
        description:"Saucy Cheesy Pizza Lorem ipsum dolor sit amet, consectetur adip.....",
    },
    {
        id: 10,
        image: "../images/Pizza5.jpg",
        name: "Extra Creamy Pizza",
        category: "Pizza",
        price: "80₹",
        description: "Extra Creamy Pizza Lorem ipsum dolor sit amet, consectetur adip.....",
    },
    {
        id: 11,
        image: "images/Steak1.jpg",
        name: 'Beef Medium Rare Steak',
        category: 'Steak',
        price: 25,
        description: 'Beef Medium Rare Steak Lorem ipsum dolor sit amet, consectetur adip.....',
    },
    {
        id: 12,
        image: "images/Steak2.jpg",
        name: "Beef Medium Steak",
        category: "Steak",
        price: "20₹",
        description:"Beef Medium Steak Lorem ipsum dolor sit amet, consectetur adip.....",
    },
    {
        id: 13,
        image: "images/Steak3.jpg",
        name: "Chicken Saucy Steak",
        category: "Steak",
        price: "10₹",
        description:"Chicken Saucy Steak Lorem ipsum dolor sit amet, consectetur adip.....",
    },
    {
        id: 14,
        image: "../images/Steak4.jpg",
        name: "Dual Medium Well Steak",
        category: "Steak",
        price: "50₹",
        description:"Chicken Saucy Steak Lorem ipsum dolor sit amet, consectetur adip.....",
    },
    {
        id: 15,
        image: "../images/Steak5.jpg",
        name: "Beef Well Done Steak",
        category: "Steak",
        price: "80₹",
        description: "Beef Well Done Steak Lorem ipsum dolor sit amet, consectetur adip.....",
    },
    {
        id: 16,
        image: "images/Salad1.jpg",
        name: 'Fresh Green Salad',
        category: 'Salad',
        price: 25,
        description: 'Fresh Green Salad Lorem ipsum dolor sit amet, consectetur adip.....',
    },
    {
        id: 17,
        image: "images/Salad2.jpg",
        name: "Mix Salad",
        category: "Salad",
        price: "20₹",
        description:"Mix Salad Lorem ipsum dolor sit amet, consectetur adip.....",
    },
    {
        id: 18,
        image: "images/Salad3.jpg",
        name: "Chicken Avacado Salad",
        category: "Salad",
        price: "10₹",
        description:"Chicken Avacado Salad Lorem ipsum dolor sit amet, consectetur adip.....",
    },
    {
        id: 19,
        image: "../images/Salad4.jpg",
        name: "Creamy Steak Salad",
        category: "Salad",
        price: "50₹",
        description:"Creamy Steak Salad Lorem ipsum dolor sit amet, consectetur adip.....",
    },
    {
        id: 20,
        image: "../images/Salad5.jpg",
        name: "Chicken Steak Salad",
        category: "Salad",
        price: "80₹",
        description: "Chicken Steak Salad Lorem ipsum dolor sit amet, consectetur adip.....",
    },
    {
        id: 21,
        image: "images/Biryani.jpg",
        name: 'Chicken Biryani',
        category: 'Pakistani',
        price: 25,
        description: 'Chicken Biryani Lorem ipsum dolor sit amet, consectetur adip.....',
    },
    {
        id: 22,
        image: "images/Handi.jpg",
        name: "Chicken Makhni Handi",
        category: "Pakistani",
        price: "20₹",
        description:"Chicken Makhni Handi Lorem ipsum dolor sit amet, consectetur adip.....",
    },
    {
        id: 23,
        image: "images/SeekhKabab.jpg",
        name: "Beef Seekh Kabab",
        category: "Pakistani",
        price: "10₹",
        description:"Beef Seekh Kabab Lorem ipsum dolor sit amet, consectetur adip.....",
    },
    {
        id: 24,
        image: "../images/Tikka.jpg",
        name: "Chicken Tikka Leg",
        category: "Pakistani",
        price: "50₹",
        description:"Chicken Tikka Leg Lorem ipsum dolor sit amet, consectetur adip.....",
    },
    {
        id: 25,
        image: "../images/BeefBoti.jpg",
        name: "Beef Bihari Boti",
        category: "Pakistani",
        price: "80₹",
        description: "Beef Bihari Boti Lorem ipsum dolor sit amet, consectetur adip.....",
    },
    {
        id: 26,
        image: "../images/Daal.jpg",
        name: "Special Daal",
        category: "Pakistani",
        price: "80₹",
        description: "Special Daal Lorem ipsum dolor sit amet, consectetur adip.....",
    },
    {
        id: 27,
        image: "../images/Nihari.jpg",
        name: "Beef Nihari",
        category: "Pakistani",
        price: "80₹",
        description: "Beef Nihari Lorem ipsum dolor sit amet, consectetur adip.....",
    },
    {
        id: 28,
        image: "../images/MixSabzi.jpg",
        name: "Mix Sabzi",
        category: "Pakistani",
        price: "80₹",
        description: "Mix Sabzi Lorem ipsum dolor sit amet, consectetur adip.....",
    },
    {
        id: 29,
        image: "../images/Pudding.jpg",
        name: "Pudding",
        category: "Desserts",
        price: "80₹",
        description: "Pudding Lorem ipsum dolor sit amet, consectetur adip.....",
    },
    {
        id: 30,
        image: "../images/RedValvet.jpg",
        name: "Raspberry Cake ",
        category: "Desserts",
        price: "80₹",
        description: "Raspberry Cake Lorem ipsum dolor sit amet, consectetur adip.....",
    },
    {
        id: 31,
        image: "../images/ChoclateCake.jpg",
        name: "Choclate Cake ",
        category: "Desserts",
        price: "80₹",
        description: "Choclate Cake Lorem ipsum dolor sit amet, consectetur adip.....",
    },
    {
        id: 32,
        image: "../images/LavaCake.jpg",
        name: "Lava Cake ",
        category: "Desserts",
        price: "80₹",
        description: "Lava Cake Lorem ipsum dolor sit amet, consectetur adip.....",
    },
]

export default Menu;